version: "3"
services:
  languagetool:
    image: erikvl87/languagetool
    ports:
      - 8010:8010 # Using default port from the image
    environment:
      langtool_languageModel: /ngrams
      Java_Xms: 512m
      Java_Xmx: 1g
    volumes:
      - /Users/alc0der/code/alc0der/languagetool/ngrams:/ngrams:ro # OPTIONAL: The location of ngrams data on the local machine
    #   # - /path/to/logback.xml:/LanguageTool/logback.xml:ro  # OPTIONAL: Overwrite the logging configuration
