direction: right

host: macOS Host {
  client: LanguageTool Client

  net: languagetool-net {
    style.stroke-dash: 5

    container: LanguageTool Container
  }

  client -> net.container: "localhost:8010"
}

internet: Internet {
  shape: cloud
}

host.net.container -> internet: blocked {
  style.stroke: red
  style.stroke-dash: 5
}
