direction: down

layers: {
  docker: {
    title: Docker Desktop on macOS {
      shape: text
      style.font-size: 24
      style.bold: true
    }

    macos: macOS
    daemon: Docker Daemon

    vm: Linux VM {
      runtime: Container Runtime
      container: Container
      runtime -> container
    }

    macos -> daemon
    daemon -> vm.runtime
  }

  native: {
    title: Apple Native Containers {
      shape: text
      style.font-size: 24
      style.bold: true
    }

    macos: macOS

    fw: Apple Virtualization Framework {
      container: Container
    }

    macos -> fw.container
  }
}
